services:
  - type: web
    name: license-admin-panel
    runtime: python
    repo: https://github.com/kumaranik646/license-admin-panel
    branch: main
    buildCommand: |
      pip cache purge
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: SECRET_KEY
        generateValue: true
      - key: PASSWORD_SALT
        generateValue: true
      - key: RENDER
        value: true
    plan: free
    healthCheckPath: /login
    autoDeploy: true
